In [47]:
import tensorflow
from tensorflow.keras import layers
import numpy as np


In [22]:
from sklearn.datasets import load_iris

data = load_iris()
X = data.data
y = data.target

In [40]:
modl = tensorflow.keras.models.Sequential([
    layers.Dense(4),
    layers.Dense(8,activation='relu'),
    layers.Dense(3,activation='softmax')
])
modl.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [41]:
modl.fit(X,y,epochs=5)

Epoch 1/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.3333 - loss: 2.8527
Epoch 2/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3333 - loss: 2.5426
Epoch 3/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3333 - loss: 2.2446
Epoch 4/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3333 - loss: 1.9707
Epoch 5/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3333 - loss: 1.7069


In [46]:
weights_biases = modl.get_weights()
weights_biases

[array([[-0.03818499, -0.68456143, -0.27941224, -0.2526086 ],
        [ 0.13307723, -0.1824413 , -0.38361967, -0.3865111 ],
        [ 0.7904801 ,  0.452753  , -0.6975522 , -0.5996568 ],
        [-0.16708785,  0.79444814,  0.13086283,  0.46063206]],
       dtype=float32),
 array([-0.0234965 ,  0.02413516,  0.0231437 ,  0.02345526], dtype=float32),
 array([[-0.11065582,  0.6610222 , -0.0016557 ,  0.2785927 ,  0.502198  ,
         -0.1090266 , -0.3546308 ,  0.59232396],
        [ 0.6131351 ,  0.00090374, -0.34731227, -0.4850279 ,  0.09272075,
          0.41281804,  0.35354784, -0.28357553],
        [-0.25099018, -0.5841308 ,  0.68910533, -0.51950336, -0.17763555,
         -0.62869877, -0.38198525, -0.3795677 ],
        [-0.09808467,  0.10612663,  0.58414584, -0.13928577,  0.32540512,
         -0.4816025 , -0.36338285, -0.36891407]], dtype=float32),
 array([ 0.0244577 ,  0.02495432,  0.        , -0.02384646,  0.02359255,
        -0.02441411,  0.02450584, -0.01417038], dtype=float32),
 arra

In [50]:
weights = []
biases = []
test_data = []
for i in range(len(weights_biases)):
    if i%2:
        weights.append(np.int16(np.round(weights_biases[i]*256)))
        print(weights)
    else:
        biases.append(np.int16(np.round(256*weights_biases[i])))
        print(biases)
for i in range(10):
    test_data.append([X[i],y[i]])
print(test_data)


[array([[ -10, -175,  -72,  -65],
       [  34,  -47,  -98,  -99],
       [ 202,  116, -179, -154],
       [ -43,  203,   34,  118]], dtype=int16)]
[array([-6,  6,  6,  6], dtype=int16)]
[array([[ -10, -175,  -72,  -65],
       [  34,  -47,  -98,  -99],
       [ 202,  116, -179, -154],
       [ -43,  203,   34,  118]], dtype=int16), array([[ -28,  169,    0,   71,  129,  -28,  -91,  152],
       [ 157,    0,  -89, -124,   24,  106,   91,  -73],
       [ -64, -150,  176, -133,  -45, -161,  -98,  -97],
       [ -25,   27,  150,  -36,   83, -123,  -93,  -94]], dtype=int16)]
[array([-6,  6,  6,  6], dtype=int16), array([ 6,  6,  0, -6,  6, -6,  6, -4], dtype=int16)]
[array([[ -10, -175,  -72,  -65],
       [  34,  -47,  -98,  -99],
       [ 202,  116, -179, -154],
       [ -43,  203,   34,  118]], dtype=int16), array([[ -28,  169,    0,   71,  129,  -28,  -91,  152],
       [ 157,    0,  -89, -124,   24,  106,   91,  -73],
       [ -64, -150,  176, -133,  -45, -161,  -98,  -97],
       [ -

In [59]:
import pickle

main_path1 = 'weights\weights.mem'
main_path2 = 'weights/biases.mem'
main_path3 = 'weights/test_data.mem'
with open(main_path1,'wb') as file:
    pickle.dump(weights,file)

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_995/4035175155.py:3: SyntaxWarning: invalid escape sequence '\w'
  main_path1 = 'weights\weights.mem'
